<?php if($crumbs && is_array($crumbs)): ?>
    <div class="breadcrumbs">
        <ul>
            <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
                <li class="<?php echo $_crumbName ?><?php if($_crumbInfo['subcategories']): ?> expandable<?php endif; ?>">
                    <?php if($_crumbInfo['link']): ?>
                        <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->escapeHtml($_crumbInfo['title']) ?>"><?php echo $this->escapeHtml($_crumbInfo['label']) ?></a>
                    <?php elseif($_crumbInfo['last']): ?>
                        <strong><?php echo $this->escapeHtml($_crumbInfo['label']) ?></strong>
                    <?php else: ?>
                        <?php echo $this->escapeHtml($_crumbInfo['label']) ?>
                    <?php endif; ?>
                    <?php if(!$_crumbInfo['last']): ?>
                        <span>/ </span>
                    <?php endif; ?>
                    <?php if($_crumbInfo['subcategories']): ?>
                        <ul class="expanded">
                        <?php foreach($_crumbInfo['subcategories'] as $_subName => $_subCrumb): ?>
                            <li class="<?php echo $_subName ?>"><a href="<?php echo $_subCrumb['link'] ?>" title="<?php echo $this->escapeHtml($_subCrumb['title']) ?>"><?php echo $this->escapeHtml($_subCrumb['label']) ?></a></li>
                        <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
